Fix sort such that it sorts [Aa - Zz]
AY2223S1-CS2103T-W13-1/tp pull request #106
Opened 2022-10-27 18:46 UTC by highorbit25

Resolves #96 
- Fix by using `String::toLowerCase` in the comparator.
- Added `Assignment` and `Participation` as valid attributes to sort by.
- Updates to UG for `sort`

2022-10-27 19:37 UTC, comicalromance requested changes

2022-10-27 19:37 UTC, comicalromance commented on src/main/java/seedu/studmap/model/student/Student.java
> +        return id.toString().toLowerCase();
hmm, might not be the best idea to modify the getIdString (and other attribute getters) directly, as there might be other methods / classes that use these getters.
maybe it's possible to modify the comparator instead?
![image](https://user-images.githubusercontent.com/7780255/198382622-dc753e12-8a6f-44b6-8acf-4bf1e95360f3.png)

2022-10-27 21:37 UTC, Piyotato commented on src/main/java/seedu/studmap/model/student/Student.java
> +        return id.toString().toLowerCase();
My bad, I suggested a poorer solution without knowing about `String::compareToIgnoreCase`. Use this solution instead?

2022-10-28 15:23 UTC, highorbit25 commented on src/main/java/seedu/studmap/model/student/Student.java
> +        return id.toString().toLowerCase();
Implemented accordingly using String::compareToIgnoreCase as second argument for comparator.

2022-11-02 05:45 UTC, Piyotato approved these changes
LGTM

2022-11-02 05:47 UTC, comicalromance approved these changes
LGTM!

2022-11-02 05:48 UTC, merged