Improve sort
AY2223S1-CS2103T-W13-1/tp pull request #75
Opened 2022-10-20 17:34 UTC by highorbit25

Logic for sorting attributes are now consolidated under the abstract class `Attribute`
- Static `isValidAttributeType` method verifies valid input attribute by checking against static  `ATTRIBUTE_SET` 
- `getAttributeComparator` returns the Comparator to sort the given attribute
- To sort new attributes in the future, we just need to add the attribute into `ATTRIBUTE_SET` and specify the Comparator in this abstract class.
- Private constructor in 'Order' class so that only the same static `ORDER_ASC` & `ORDER_DSC` is used as the sorting order.
- Fix #66 
- Resolves #64

2022-10-20 17:45 UTC, highorbit25 commented
Did not implement Attribute as a super class for attributes to inherit as per suggested in previous PR discussion.
Felt that having each attribute that extends Attribute overwrite getAttributeComparator() individually would not value add much. Having all the Comparator and valid attributeTypes located within the abstract Attribute class itself for ease of future development seems sufficient for now.
Open for further discussion!

2022-10-21 01:26 UTC, Piyotato requested changes

2022-10-21 01:26 UTC, Piyotato commented on src/main/java/seedu/studmap/model/attribute/Attribute.java
> +            switch (attributeType) {
Should use `enum` for `AttributeType`. Use `valueOf` to parse the input in the parser. See: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Enum.html#valueOf(java.lang.Class,java.lang.String)

2022-10-23 12:52 UTC, highorbit25 commented on src/main/java/seedu/studmap/model/attribute/Attribute.java
> +            switch (attributeType) {
Agreed, implemented accordingly. Thanks!

2022-10-24 07:04 UTC, Piyotato approved these changes
LGTM

2022-10-24 10:48 UTC, lpohsien approved these changes
Good use of OOP to make sorting extensible. LGTM.

2022-10-24 10:48 UTC, lpohsien commented on src/main/java/seedu/studmap/model/attribute/AttributeType.java
> +public enum AttributeType {
Just a thought, will it be better (in terms of organization and readability) if AttributeType is an inner class of Attribute? Or is there any particular reason requires the AttributeType to be separated?

2022-10-24 14:46 UTC, merged