Filter assignments, module and tag
AY2223S1-CS2103T-W13-1/tp pull request #92
Opened 2022-10-26 16:41 UTC by dr-arrgghh

#88

2022-10-26 17:31 UTC, Piyotato requested changes

2022-10-26 17:31 UTC, Piyotato commented on src/main/java/seedu/studmap/logic/commands/FilterCommand.java
> +    public FilterCommand(TagContainsKeywordsPredicate tPredicate, ModuleContainsKeywordsPredicate mPredicate,
At this point, should it just take in a `List<Predicate<Student>>`?

2022-10-26 17:31 UTC, Piyotato commented on src/main/java/seedu/studmap/logic/parser/FilterCommandParser.java
> +        }
Shouldn't this be handled by `ArgumentMultimap`? Also, we should avoid these magic strings, especially when we do have static versions of these tags.

2022-10-26 17:31 UTC, Piyotato commented on src/main/java/seedu/studmap/logic/commands/FilterCommand.java
> +            + "Example: " + COMMAND_WORD + "t/" + " friends";
`PREFIX_TAG` shouldn't be hardcoded here.

2022-10-26 17:31 UTC, Piyotato commented on src/main/java/seedu/studmap/model/ModelManager.java
> +    }
Do we really need all these methods with the same parameters and code, but differently named?

2022-10-26 17:31 UTC, Piyotato commented on src/main/java/seedu/studmap/model/student/AssignmentContainsKeywordsPredicate.java
> +public class AssignmentContainsKeywordsPredicate implements Predicate<Student> {
Actually, should this just be an inner class in `FilterCommand`, if not used elsewhere? Also applies to the other predicates.

2022-10-26 17:43 UTC, Piyotato commented on src/main/java/seedu/studmap/logic/commands/FilterCommand.java
> +    public FilterCommand(TagContainsKeywordsPredicate tPredicate, ModuleContainsKeywordsPredicate mPredicate,
Yup, predicates can be composed with logical operators so it can actually just be a single one.

2022-10-27 15:49 UTC, dr-arrgghh commented on src/main/java/seedu/studmap/model/student/AssignmentContainsKeywordsPredicate.java
> +public class AssignmentContainsKeywordsPredicate implements Predicate<Student> {
For this part im a bit unsure since filtercommandparser uses the different predicates

2022-10-27 16:51 UTC, Piyotato commented on src/test/java/seedu/studmap/logic/commands/AddCommandTest.java
> +            throw new AssertionError("This method should not be called,");
You accidentally changed the period to a comma here

2022-10-27 17:38 UTC, dr-arrgghh commented on src/main/java/seedu/studmap/logic/parser/FilterCommandParser.java
> +        if (trimmedArgs.length() == 2 || trimmedArgs.isEmpty()) {
Its to ensure that user do not input an empty argument after specifying the prefix. For example, "filter t/ " should throw an exception too just like "filter". Only instances such as "filter t/ friends" are considered valid.

2022-10-27 17:51 UTC, Piyotato approved these changes
LGTM

2022-10-27 17:51 UTC, Piyotato commented on src/main/java/seedu/studmap/logic/parser/FilterCommandParser.java
> +        if (trimmedArgs.length() == 2 || trimmedArgs.isEmpty()) {
You can check whether the optional returned from `argMultimap::getValue` contains an empty string actually

2022-10-27 18:55 UTC, merged